version: '3'

services:
  db:
    container_name: postgis
    hostname: postgis
    image: postgis
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - ./db/.env

    volumes:
      - postgis:/var/lib/postgis/data
    ports:
      - "5432:5432"

  python-app:
    image: postgis  # Use the same image as the 'db' service
    container_name: python-app
    build: ./  # Build context is the current directory
    command: ["python3", "main.py"]  # Command to run your Python script
    depends_on:
      - db

volumes:
  postgis:
    name: postgis
